---
title: "State Population and County Economic Connectedness"
author: "Your Name"
format: html
execute: 
  echo: false
---

What is the relationship between state population and the average county economic connectedness in a state?

```{r}
#| output: false
#| label: set up

library(tidyverse)

x <- read_rds("data/ec.rds")
```



```{r}
#| label: plotting
x |> 
  mutate(state = str_replace(county_name, ".*, ", "")) |>
  select(county_name, ec_county, pop2018, state)|>
  summarise(total_pop = sum(pop2018),
            ec = mean(ec_county),
            .by = state)|>
  drop_na()|>
  ggplot(mapping = aes(x = total_pop,
                       y = ec))+
  geom_point()+
  geom_smooth(formula = y ~ x,
              method = "lm",
              se = FALSE)+
  scale_x_log10(labels = scales::comma_format())
  labs(title = "Economic Connectiveness and Population in the US",
       subtitle = "Bigger states have counties with lower average economic\n connectivenss",
       x = "Total Population")
```


